<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mcfunction</string>
		<string>bolt</string>
	</array>
	<key>name</key>
	<string>Mcfunction</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#root</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>^\s*(#[&gt;!])(.+)$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.block.mcfunction</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.bold.mcfunction</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.block.mcfunction</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?!#)</string>
					<key>name</key>
					<string>meta.comments</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments_block</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.line.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#.*$</string>
					<key>name</key>
					<string>meta.comments</string>
				</dict>
			</array>
		</dict>
		<key>comments_block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>^\s*#[&gt;!]</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.block.mcfunction</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.comments_block</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments_block_emphasized</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>^\s*#</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.block.mcfunction</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.comments_block</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments_block_normal</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments_block_emphasized</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments_block_special</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>markup.bold.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\S+</string>
					<key>name</key>
					<string>meta.comments_block_emphasized</string>
				</dict>
			</array>
		</dict>
		<key>comments_block_normal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments_block_special</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.block.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\S+</string>
					<key>name</key>
					<string>meta.comments_block_normal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#whitespace</string>
				</dict>
			</array>
		</dict>
		<key>comments_block_special</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>markup.heading.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>@\S+</string>
					<key>name</key>
					<string>meta.comments_block_special</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#resource-name</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.other.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[#%$][A-Za-z0-9_.#%$]+</string>
					<key>name</key>
					<string>meta.comments_block_special</string>
				</dict>
			</array>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>literal.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\.\.</string>
					<key>name</key>
					<string>meta.literals</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.other.psuedo.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(true|false)</string>
					<key>name</key>
					<string>meta.literals</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[A-Za-z_]+</string>
					<key>name</key>
					<string>meta.literals</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.byte.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[0-9]b</string>
					<key>name</key>
					<string>meta.literals</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.float.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[+-]?\d*\.?\d+([eE]?[+-]?\d+)?[df]?\b</string>
					<key>name</key>
					<string>meta.literals</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[+-]?\d+\b</string>
					<key>name</key>
					<string>meta.literals</string>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>"</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.mcfunction</string>
						</dict>
					</dict>
					<key>end</key>
					<string>("|$)</string>
					<key>name</key>
					<string>meta.literals</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#literals_string-double</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>'</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.mcfunction</string>
						</dict>
					</dict>
					<key>end</key>
					<string>('|$)</string>
					<key>name</key>
					<string>meta.literals</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#literals_string-single</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>literals_string-double</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>meta.literals_string-double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro-name</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[^\\"]</string>
					<key>name</key>
					<string>meta.literals_string-double</string>
				</dict>
			</array>
		</dict>
		<key>literals_string-single</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.character.escape.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>meta.literals_string-single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro-name</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[^\\']</string>
					<key>name</key>
					<string>meta.literals_string-single</string>
				</dict>
			</array>
		</dict>
		<key>macro-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.template-expression.begin.mcfunction</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.mcfunction</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.template-expression.end.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$\()([A-Za-z0-9_]+)(\))</string>
					<key>name</key>
					<string>meta.macro-name</string>
				</dict>
			</array>
		</dict>
		<key>names</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>whitespace.mcfunction</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.flow.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(\s*)([a-z_]+)(?=\s)</string>
					<key>name</key>
					<string>meta.names.mcfunction</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>whitespace.mcfunction</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.italic.mcfunction</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.control.flow.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(\s*)(\$)([a-z_]*)</string>
					<key>name</key>
					<string>meta.names.mcfunction</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyboard.control.flow.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=run)\s+[a-z_]+(?=\s)</string>
					<key>name</key>
					<string>meta.names.mcfunction</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.uuid.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b[0-9a-fA-F]+(?:-[0-9a-fA-F]+){4}\b</string>
					<key>name</key>
					<string>meta.names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#resource-name</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[A-Za-z]+(?=\W)</string>
					<key>name</key>
					<string>meta.names</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[A-Za-z_][A-Za-z0-9_.#%$]*</string>
					<key>name</key>
					<string>meta.names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#macro-name</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.other.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[#%$][A-Za-z0-9_.#%$]+</string>
					<key>name</key>
					<string>meta.names</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[\-~%^?!+*&lt;&gt;\\/|&amp;=.:,]</string>
					<key>name</key>
					<string>meta.operators</string>
				</dict>
			</array>
		</dict>
		<key>property</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>\{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.mcfunction</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.property.curly</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#property_key</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#property_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>\[</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.mcfunction</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>meta.property.square</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#property_key</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#property_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>\(</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.mcfunction</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.property.paren</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#resource-name</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#property_key</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#property_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>property_key</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#?[a-z_][a-z_\.\-]*\:[a-z0-9_\.\-/]+(?=\s*\=)</string>
					<key>name</key>
					<string>meta.property_key</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#?[a-z_][a-z0-9_\.\-/]+</string>
					<key>name</key>
					<string>meta.property_key</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[A-Za-z_\-\+]+</string>
					<key>name</key>
					<string>meta.property_key</string>
				</dict>
			</array>
		</dict>
		<key>property_value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#?[a-z_][a-z_\.\-]*\:[a-z0-9_\.\-/]+</string>
					<key>name</key>
					<string>meta.property_value</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#?[a-z_][a-z0-9_\.\-/]+</string>
					<key>name</key>
					<string>meta.property_value</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
			</array>
		</dict>
		<key>resource-name</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#?[a-z_][a-z_.-]*:[a-z0-9_./-]+</string>
					<key>name</key>
					<string>meta.resource-name</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#?[a-z0-9_\.\-]+\/[a-z0-9_\.\-\/]+</string>
					<key>name</key>
					<string>meta.resource-name</string>
				</dict>
			</array>
		</dict>
		<key>root</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#names</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#property</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selectors</string>
				</dict>
			</array>
		</dict>
		<key>selectors</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.class.mcfunction</string>
						</dict>
					</dict>
					<key>match</key>
					<string>@[a-z]</string>
					<key>name</key>
					<string>meta.selectors</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mcfunction</string>
	<key>uuid</key>
	<string>8918dadd-8ebe-42d9-b1e9-0489ab228d9d</string>
</dict>
</plist>
